# Generated by Django 5.1.2 on 2024-12-14 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
    ]
