# Generated by Django 5.1.2 on 2024-12-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_remove_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
